### ISSUE TITLE
Add new etf BTC

### ISSUE THREAD

**Issue by BuildWithData** [BuildWithData/BTC-ETF-Tracker#91]
Grayscale has released their mini etf with ticker BTC, we have to add this to the repo

Already added scraper, check branch ```feature/btc```, next is to write code to extract data and create tables

**Comment by aditya2111** [comment]
what is the website link from which we need to scrape the data?

**Comment by Krishpandya682** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by BuildWithData** [comment]
hey @Krishpandya682 do you wanna help out with this ?

got an email where you were asking this, but now I see no comments here

let me know :)

**Comment by BuildWithData** [comment]
thanks @H-Blues for your contribution, just merged your code into ```feature/btc```

I have added a few commits on the feature branch to:

- add tables to raw layer (also added src/db/tmp_btc.py to only add BTC tables to your existing db)
- add BTC to update_raw runner

but when I try to extract the data and save them into tables it fails, I guess ```BTC.extract``` needs some fixs, it is not probably identical to GBTC's

can you have a look ?

**Comment by H-Blues** [comment]
Hey @BuildWithData , I have submitted a new PR and it works in my desktop now. 

It is a date format conversion problem. Sorry for that.

**Comment by BuildWithData** [comment]
thanks for you help @H-Blues 

I fixed a minor thing in the scraper and dropped the ```update_db``` as we gonna implement this in a separate merge request, you can find both changes in ```feature/btc``` branch

can you open a merge request so I can merge and keep it as your contribution ?

**Comment by H-Blues** [comment]
Hi, @BuildWithData 

I'm glad to contribute (even though it's a very simple task).  🎉

Just to confirm, do you want me to submit a merge request to the `main` branch? 

And would merging a updated `feature/btc` be more convenient for your work? Since strictly speaking, I only did a small part of it.

**Comment by BuildWithData** [comment]
can't you open a merge request to merge ```feature/btc``` into ```main``` ?

**Comment by BuildWithData** [comment]
https://github.com/BuildWithData/BTC-ETF-Tracker/pull/95

https://github.com/BuildWithData/BTC-ETF-Tracker/pull/97
