### ISSUE TITLE
Request for Updating Scraped Data

### ISSUE THREAD

**Issue by H-Blues** [BuildWithData/BTC-ETF-Tracker#92]
Hi Team, 

Thanks for your great job! I really appreciate it. 

This issue is to kindly ask for the update of the scraping data, which starts from Feb 23rd and ends on May 19th.

Many thanks for your help.

**Comment by BuildWithData** [comment]
just uploaded the data as of today

would you like to contribute to the project ? [this](https://github.com/BuildWithData/BTC-ETF-Tracker/issues/91) would be a good start

**Comment by H-Blues** [comment]
Thanks for the updating. I will try to do #91 if my time is available.
